//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic_card.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magic_card.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 RK=r7kWSuU7cf; luin=o1224842990; lskey=00010000b509b4900b2ba9f2b7fe37d26ef9db83830692ee2c5817ecd393da90cd6af892eb57b6eef52d86e1; ptui_loginuin=1224842990; pgv_pvi=9572238336; pac_uid=1_1224842990; o_cookie=1224842990; LW_uid=s184w8V9w4x8x4T649Z1P393K7; eas_sid=Y1b4M8h9u4S8j4u6e9q3I0R9M2; LW_sid=s1N4N8C9Y4T8p4H77153H1o9o8; _qpsvr_localtk=0.9220434585235773; yearvip=; flaversion=; cardsrc=0; pt2gguin=o1224842990; uin=o1224842990; skey=@fJA0zzHlq; ptisp=ctc; ptcz=fdba4d8aa85147a65c92dbf22ef827d3609b8cd0ff8189d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
    }
}
